name: ujjaini
recipe: drupal9
config:
  php: '8.1'
  via: apache:4
  webroot: .
  xdebug: true
  drupal: true
services:
  pma:
    type: phpmyadmin
    hosts:
      - database
proxy:
  pma:
    - phpmyadmin.lndo.site
tooling:
  drupal:
    service: appserver
